#!/usr/bin/env bash
# Installs Nginx server in local commputer
# server listens @ port 80
# it returns Hello World with a GET
# request curl

apt-get update
apt-get install -y nginx
service nginx restart
echo "Hello World" > /var/www/html/index.nginx-debian.html
