#!/usr/bin/env bash
# Installs Nginx server in local commputer
# server listens @ port 80

apt-get -y update
apt-get install -y nginx
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
