#!/usr/bin/env bash
#This bash script pings an addredd passed as an argument
# It accepts a string as an argument and displays
#Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument is passed.
# This displays ping of 5 times

if [[ $# -gt 1 ]];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
