#!/usr/bin/env bash
#Script that displays Best School 1o times.
#But displays Hi on the ninth time.

c=1
while [ $c -le 10 ]
do
	echo "Best School"
	if [ $c -eq 9 ]
	then
		echo "Hi"
	fi

	((c++))
done
