#!/usr/bin/env bash
# This bash script displays the following:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for result  in *
do
	echo "$result" | cut -d "-" -f 2
done
